config/routes.rb
Rails.application.routes.draw do

  root "dashboard#tech"

  get "tech" => "dashboard#tech", as: "tech"
  get "resources" => "dashboard#resources", as: "resources"
  get "info" => "dashboard#org", as: "org"
  get "logo" => "dashboard#logo", as: "logo"

end

app/models/event.rb
class Event < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/dashboard/logo.html.slim
.logo-brand.text-center
  = t("layouts.header.title")

app/views/dashboard/org.html.slim
.row
  .col-sm-3
    ul.nav.nav-stacked.nav-pills
      li.active
        a href=""
          i.glyphicon.glyphicon-time>
          | Getting Started
      li
        a href="#"
          i.glyphicon.glyphicon-home>
          | Booking a Venue
      li
        a href="#"
          i.glyphicon.glyphicon-thumbs-up>
          | How to Advertise
      li
        a href="#"
          i.glyphicon.glyphicon-shopping-cart>
          | What you need
      li
        a href="#"
          i.glyphicon.glyphicon-briefcase>
          | Press Packs
  .col-sm-9
    h2 Getting your own Generation Code meetup started
    p
      | Nullam sagittis. Maecenas malesuada. Nulla sit amet est. Curabitur at lacus ac velit ornare lobortis. Donec vitae orci sed dolor rutrum auctor.
      br
      | Suspendisse eu ligula. Pellentesque posuere. Cras dapibus. Fusce ac felis sit amet ligula pharetra condimentum. Praesent congue erat at massa.
    .alert.alert-info
      | Praesent egestas tristique nibh. Phasellus ullamcorper ipsum rutrum nunc. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Cras varius. Suspendisse potenti.
    p
      | Ut non enim eleifend felis pretium feugiat. Aenean vulputate eleifend tellus. Sed libero. Duis leo. Proin magna.
    h3 How much of my time does it take?
    p
      | Phasellus volutpat, metus eget egestas mollis, lacus lacus blandit dui, id egestas quam mauris ut lacus. Donec interdum, metus et hendrerit aliquet, dolor diam sagittis ligula, eget egestas libero turpis vel mi. Vivamus in erat ut urna cursus vestibulum. Duis leo. Cras ultricies mi eu turpis hendrerit fringilla.
      br
      | Nullam dictum felis eu pede mollis pretium. Fusce vel dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Etiam ut purus mattis mauris sodales aliquam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce id purus.
      br
      | Quisque libero metus, condimentum nec, tempor a, commodo mollis, magna. Curabitur a felis in nunc fringilla tristique. Aenean posuere, tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus. Etiam sollicitudin, ipsum eu pulvinar rutrum, tellus ipsum laoreet sapien, quis venenatis ante odio sit amet eros. Suspendisse enim turpis, dictum sed, iaculis a, condimentum nec, nisi.
    hr
    h2 How to find a venue
    p
      | Nunc egestas, augue at pellentesque laoreet, felis eros vehicula leo, at malesuada velit leo quis pede. Fusce vel dui. Proin magna. Aenean commodo ligula eget dolor. Pellentesque auctor neque nec urna.
      br
      | Praesent nonummy mi in odio. Aliquam erat volutpat. Ut non enim eleifend felis pretium feugiat. Fusce neque. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero.
      br
      | Mauris sollicitudin fermentum libero. Nunc nulla. Quisque libero metus, condimentum nec, tempor a, commodo mollis, magna. Proin magna. Cras id dui.
      br
      | Sed fringilla mauris sit amet nibh. Proin viverra, ligula sit amet ultrices semper, ligula arcu tristique sapien, a accumsan nisi mauris ac eros. Quisque id odio. Aenean vulputate eleifend tellus. Curabitur vestibulum aliquam leo.
    h3 Approaching a venue for free access
    p
      | Vestibulum volutpat pretium libero. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Quisque id mi. Donec elit libero, sodales nec, volutpat a, suscipit non, turpis. Quisque libero metus, condimentum nec, tempor a, commodo mollis, magna.
      br
      | Vestibulum suscipit nulla quis orci. Maecenas vestibulum mollis diam. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Quisque ut nisi.
    blockquote
      | Dear Sir/Madam,
      br
      br
      | Suspendisse feugiat. Donec mi odio, faucibus at, scelerisque quis, convallis in, nisi. Vestibulum fringilla pede sit amet augue. Curabitur a felis in nunc fringilla tristique. Praesent porttitor, nulla vitae posuere iaculis, arcu nisl dignissim dolor, a pretium mi sem ut ipsum.
      br
      | Etiam rhoncus. Nulla consequat massa quis enim. In ac felis quis tortor malesuada pretium. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Sed augue ipsum, egestas nec, vestibulum et, malesuada adipiscing, dui.
      br
      | Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Praesent ac sem eget est egestas volutpat. Donec sodales sagittis magna. Suspendisse potenti. Aenean ut eros et nisl sagittis vestibulum.
      br
      br
      | Yours Failthfully,
      br
      | Joe Bloggs

    hr

    h2 How to get the word out
    p
      | Sed in libero ut nibh placerat accumsan. Suspendisse feugiat. Phasellus leo dolor, tempus non, auctor et, hendrerit quis, nisi. Donec mollis hendrerit risus. Mauris sollicitudin fermentum libero.
      br
      | Fusce fermentum odio nec arcu. Nullam sagittis. Duis leo. Etiam feugiat lorem non metus. Fusce vel dui.
    .alert.alert-info
      | Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue, elit erat euismod orci, ac placerat dolor lectus quis orci. Maecenas vestibulum mollis diam. Quisque rutrum. Curabitur turpis. Vestibulum turpis sem, aliquet eget, lobortis pellentesque, rutrum eu, nisl.
    p
      | Cras non dolor. Aliquam eu nunc. Duis lobortis massa imperdiet quam. Nullam sagittis. Proin viverra, ligula sit amet ultrices semper, ligula arcu tristique sapien, a accumsan nisi mauris ac eros.
      br
      | Vestibulum fringilla pede sit amet augue. Curabitur at lacus ac velit ornare lobortis. Vivamus aliquet elit ac nisl. Aenean commodo ligula eget dolor. Curabitur ullamcorper ultricies nisi.

    h2 What you need on the day itself
    p
      | Fusce ac felis sit amet ligula pharetra condimentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus magna. Fusce vulputate eleifend sapien. Pellentesque egestas, neque sit amet convallis pulvinar, justo nulla eleifend augue, ac auctor orci leo non est.
      br
      | Duis leo. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Praesent ac sem eget est egestas volutpat. In turpis. Nulla consequat massa quis enim.
      br
      | Curabitur turpis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent ac massa at ligula laoreet iaculis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.
      br
      | Morbi mollis tellus ac sapien. Curabitur turpis. Nunc interdum lacus sit amet orci. Vivamus laoreet. Donec interdum, metus et hendrerit aliquet, dolor diam sagittis ligula, eget egestas libero turpis vel mi.
      br
      | Aenean viverra rhoncus pede. Nam adipiscing. Sed libero. Fusce risus nisl, viverra et, tempor et, pretium in, sapien. Sed in libero ut nibh placerat accumsan.

app/views/dashboard/resources.html.slim
.row
  .col-sm-12
    h1.text-center Gaming

.row
  .col-sm-12
    p.text-center
      | Want to make the next Minecraft or just want to learn to code in a fun,
      |  goal driven environment? You can find all the resources you need to get
      |  started whatever your experience level right here:
      hr

.row
  .col-sm-12
    h2.text-center Getting started

.row
  .col-sm-4
    .row
      .col-xs-12.shifted-right
        figure.snip0013.border
          = image_tag "minecraft_01.png"
          div
            a href="#" title="Send resource to someone" data-toggle="modal" data-target="#myModal"
              i.ion-link.left-icon
            a href="http://minemum.com/getting-started" title="View resource" target="_blank"
              i.ion-forward.right-icon
    .row
      .col-xs-12.text-center
        | Installing Minecraft
        br
        small Install the world's most downloaded creative game

  .col-sm-4
    .row
      .col-xs-12.shifted-right
        figure.snip0013.border
          = image_tag "minecraft_02.jpg"
          div
            a href="#" title="Send resource to someone" data-toggle="modal" data-target="#myModal"
              i.ion-link.left-icon
            a href="http://minemum.com/splash" title="View resource" target="_blank"
              i.ion-forward.right-icon
    .row
      .col-xs-12.text-center
        | Customize Minecraft Greeting
        br
        small Personalize your game with fun messages on start up

  .col-sm-4
    .row
      .col-xs-12.shifted-right
        figure.snip0013.border
          = image_tag "code_combat.jpg"
          div
            a href="#" title="Send resource to someone" data-toggle="modal" data-target="#myModal"
              i.ion-link.left-icon
            a href="http://codecombat.com" title="View resource" target="_blank"
              i.ion-forward.right-icon
    .row
      .col-xs-12.text-center
        | Code Combat
        br
        small Learn to code by playing a game

.row
  .col-sm-4
    .row
      .col-xs-12.shifted-right
        figure.snip0013.border
          = image_tag "minecraft_3.png"
          div
            a href="#" title="Send resource to someone" data-toggle="modal" data-target="#myModal"
              i.ion-link.left-icon
            a href="http://code.org/mc" title="View resource" target="_blank"
              i.ion-forward.right-icon
    .row
      .col-xs-12.text-center
        | Mincraft Hour of Code
        br
        small Use blocks of code in a minecraft adventure

  .col-sm-4
    .row
      .col-xs-12.shifted-right
        figure.snip0013.border
          = image_tag "flap.png"
          div
            a href="#" title="Send resource to someone" data-toggle="modal" data-target="#myModal"
              i.ion-link.left-icon
            a href="https://studio.code.org/flappy/1" title="View resource" target="_blank"
              i.ion-forward.right-icon
    .row
      .col-xs-12.text-center
        | Make flappy bird
        br
        small Recreate the flaptastic experience yourself

  .col-sm-4
    .row
      .col-xs-12.shifted-right
        figure.snip0013.border
          = image_tag "avengers.png"
          div
            a href="#" title="Send resource to someone" data-toggle="modal" data-target="#myModal"
              i.ion-link.left-icon
            a href="https://www.codeavengers.com" title="View resource" target="_blank"
              i.ion-forward.right-icon
    .row
      .col-xs-12.text-center
        | Code Avengers
        br
        small Program a game with a real programming lanauage

.row
  .col-xs-12
    hr
.row
  .col-sm-12
    h2.text-center Intermediate

.row
  .col-sm-4
    .row
      .col-xs-12.shifted-right
        figure.snip0013.border
          = image_tag "ruby_warrior.png"
          div
            a href="#" title="Send resource to someone" data-toggle="modal" data-target="#myModal"
              i.ion-link.left-icon
            a href="https://www.bloc.io/ruby-warrior#/" title="View resource" target="_blank"
              i.ion-forward.right-icon
    .row
      .col-xs-12.text-center
        | Ruby Warrior
        br
        small A triumphant quest of adventure, love & destiny

  .col-sm-4
    .row
      .col-xs-12.shifted-right
        figure.snip0013.border
          = image_tag "flowlab.png"
          div
            a href="#" title="Send resource to someone" data-toggle="modal" data-target="#myModal"
              i.ion-link.left-icon
            a href="http://flowlab.io/video_tutorials" title="View resource" target="_blank"
              i.ion-forward.right-icon
    .row
      .col-xs-12.text-center
        | Flowlab
        br
        small Create simple games right in your browser

  .col-sm-4
    .row
      .col-xs-12.shifted-right
        figure.snip0013.border
          = image_tag "scratch_02.png"
          div
            a href="#" title="Send resource to someone" data-toggle="modal" data-target="#myModal"
              i.ion-link.left-icon
            a href="https://scratch.mit.edu/about/" title="View resource" target="_blank"
              i.ion-forward.right-icon
    .row
      .col-xs-12.text-center
        | Scratch
        br
        small Interactive, in-browser story builder

.row
  .col-xs-12
    hr
.row
  .col-sm-12
    h2.text-center Advanced

.row
  .col-sm-4
    .row
      .col-xs-12.shifted-right
        figure.snip0013.border
          = image_tag "unity_space.png"
          div
            a href="#" title="Send resource to someone" data-toggle="modal" data-target="#myModal"
              i.ion-link.left-icon
            a href="https://unity3d.com/learn/tutorials/projects/space-shooter-tutorial" title="View resource" target="_blank"
              i.ion-forward.right-icon
    .row
      .col-xs-12.text-center
        | Unity Space Combat
        br
        small Build an arcade style space shooter

  .col-sm-4
    .row
      .col-xs-12.shifted-right
        figure.snip0013.border
          = image_tag "android_02.png"
          div
            a href="#" title="Send resource to someone" data-toggle="modal" data-target="#myModal"
              i.ion-link.left-icon
            a href="http://developer.android.com/training/index.html" title="View resource" target="_blank"
              i.ion-forward.right-icon
    .row
      .col-xs-12.text-center
        | Native Android Gaming
        br
        small Build low level games for android devices

  .col-sm-4
    .row
      .col-xs-12.shifted-right
        figure.snip0013.border
          = image_tag "matrix.jpg"
          div
            a href="#" title="Send resource to someone" data-toggle="modal" data-target="#myModal"
              i.ion-link.left-icon
            a href="http://codecombat.com" title="View resource" target="_blank"
              i.ion-forward.right-icon
    .row
      .col-xs-12.text-center
        | Vector Matrix Programming
        br
        small Help Neo beat Agent Smith

#myModal.modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4#myModalLabel.modal-title Share a resource
      .modal-body
        = form_tag "" do
          .form-group
            = label_tag :email
            = email_field_tag :email, "", class: "form-control"
      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button"  Cancel
        button.btn.btn-primary type="button" data-dismiss="modal" Send

app/views/dashboard/tech.html.slim
.row
  .col-sm-12
    h1.text-center Search by Technology

.row
  .col-sm-12
    p.text-center
      | Already have some experience with a tool or know what it is you want to
      |  learn? Search by technology to find the right resources for you:
      hr

.row
  .col-sm-4
    figure.snip0013
      = image_tag "android.jpg"
      div
        a href=resources_path
          span.text Android
  .col-sm-4
    figure.snip0013
      = image_tag "apple.png"
      div
        a href=resources_path
          span.text iOS
  .col-sm-4
    figure.snip0013
      = image_tag "python.png"
      div
        a href=resources_path
          span.text Python
.row
  .col-sm-4
    figure.snip0013
      = image_tag "ruby.png"
      div
        a href=resources_path
          span.text Ruby
  .col-sm-4
    figure.snip0013
      = image_tag "vr.jpg"
      div
        a href=resources_path
          span.text VR
  .col-sm-4
    figure.snip0013
      = image_tag "wearables.jpg"
      div
        a href=resources_path
          span.text.smaller Wearables
.row
  .col-sm-4
    figure.snip0013
      = image_tag "scratch.png"
      div
        a href=resources_path
          span.text Scratch
  .col-sm-4
    figure.snip0013
      = image_tag "pi.png"
      div
        a href=resources_path
          span.text.smaller Raspberry Pi
  .col-sm-4
    figure.snip0013
      = image_tag "home.png"
      div
        a href=resources_path
          span.text.smaller
            | Home
            br
            | Automation

app/views/layouts/_header.html.slim
= navbar do
  = vertical do
    = link_to t(".title"), root_path
  = horizontal do
    = nav class: 'navbar-left' do
      = link_to t(".technologies"), tech_path
      = link_to t(".resources"), resources_path
      = link_to t(".contact"), root_path
    = nav class: 'navbar-right' do
      = link_to t(".info_for_organizers"), org_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Generation Code</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/header" %>
  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>